apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eisheilige2026
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - issuer.yaml
images:
  - name: registry.144.91.77.245.sslip.io/eisheilige2026
    newTag: facf9e06e886aaa76c348c7d5e9d823c4bb771cc
