apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eisheilige2026
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - issuer.yaml
images:
  - name: registry.144.91.77.245.sslip.io/eisheilige2026
H73ff7f26aaa6059c5b8522b88583268fc58d8f
